// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: like.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const toggleLike = `-- name: ToggleLike :exec
WITH deleted AS (
DELETE FROM likes WHERE user_id = $1 AND tweet_id = $2
    RETURNING id, user_id, tweet_id, created_at
)
INSERT INTO likes (user_id, tweet_id, created_at)
SELECT $1, $2, now()
    WHERE NOT EXISTS (SELECT 1 FROM deleted)
`

type ToggleLikeParams struct {
	UserID  pgtype.Int8 `json:"user_id"`
	TweetID pgtype.Int8 `json:"tweet_id"`
}

func (q *Queries) ToggleLike(ctx context.Context, arg ToggleLikeParams) error {
	_, err := q.db.Exec(ctx, toggleLike, arg.UserID, arg.TweetID)
	return err
}
