// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"time"
)

// A user cannot follow themselves.
type Followers struct {
	ID          int64       `json:"id"`
	FollowerID  int64 	    `json:"follower_id"`
	FollowingID int64	    `json:"following_id"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Likes struct {
	ID        int64       `json:"id"`
	UserID    int64		  `json:"user_id"`
	TweetID   int64		  `json:"tweet_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type Tweets struct {
	ID        int64       `json:"id"`
	UserID    int64 	  `json:"user_id"`
	TweetID   int64 	  `json:"tweet_id"`
	Content   string      `json:"content"`
	FileUrl   string `json:"file_url"`
	CreatedAt time.Time   `json:"created_at"`
}

type Users struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// should be unique
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
